language: rust
rust:
  - 1.32.0
  - stable
  - nightly
script:
  - cargo test
  - if [ $TRAVIS_RUST_VERSION == "nightly" ]; then
        env RUSTFLAGS="-Z sanitizer=leak" cargo +nightly test --target x86_64-unknown-linux-gnu;
    fi
