[package]
name = "svgdom"
version = "0.3.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "dom"]
license = "MPL-2.0"
description = "Library to represent an SVG as a DOM."
repository = "https://github.com/RazrFalcon/libsvgdom"
documentation = "https://docs.rs/svgdom/"
readme = "README.md"

[dependencies]
float-cmp = "0.2.3"
# simplecss = { git = "https://github.com/RazrFalcon/simplecss.git" }
simplecss = "0.1.0"

[dependencies.svgparser]
# latest public
# git = "https://github.com/RazrFalcon/libsvgparser.git"
# local copy
# path = "../svgparser"
# from crates
version = "0.2.0"

[dev-dependencies]
time = "0.1"

[features]
default = ["parsing"]
parsing = []
