[package]
name = "svgdom"
# When updating version, also modify html_root_url in the lib.rs and in the README
version = "0.13.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "dom"]
license = "MIT/Apache-2.0"
description = "Library to represent an SVG as a DOM."
repository = "https://github.com/RazrFalcon/svgdom"
documentation = "https://docs.rs/svgdom/"
readme = "README.md"

[badges]
travis-ci = { repository = "RazrFalcon/svgdom" }

[dependencies]
log = "0.4.5"
simplecss = "0.1"
slab = "0.4"
#svgtypes = "0.1.1"
svgtypes = { git = "https://github.com/RazrFalcon/svgtypes", rev = "47d16af" }
roxmltree = "0.1"

[dev-dependencies]
time = "0.1"
bencher = "0.1"
pretty_assertions = "0.5.1"

[[bench]]
name = "parser"
harness = false

[lib]
path = "src/lib.rs" # for cargo-readme
doctest = true
