[package]
name = "svgdom"
# When updating version, also modify html_root_url in the lib.rs and in the README
version = "0.12.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "dom"]
license = "MIT/Apache-2.0"
description = "Library to represent an SVG as a DOM."
repository = "https://github.com/RazrFalcon/svgdom"
documentation = "https://docs.rs/svgdom/"
readme = "README.md"

[badges]
travis-ci = { repository = "RazrFalcon/svgdom" }

[dependencies]
failure = "0.1.1"
log = "0.4"
simplecss = "0.1.0"
slab = "0.4.0"
svgtypes = { git = "https://github.com/RazrFalcon/svgtypes", rev = "4d279a5" }

[dev-dependencies]
time = "0.1"
bencher = "0.1"

[[bench]]
name = "parser"
harness = false

[lib]
doctest = true
